#!/usr/bin/env python

from __future__ import print_function

import numpy as np
import sys
from datetime import datetime

inp = np.loadtxt(sys.stdin)

# time freq lvl

nfreqs = len(np.unique(inp[:,1]))
nrows = len(inp) / nfreqs

#out = inp[0:nfreqs*nrows,2].reshape((nrows, nfreqs))

for i in xrange(nrows):
    sys.stdout.write("\t%f\t%f\n" % (inp[nfreqs * i, 0], np.sum(inp[nfreqs * i:nfreqs * (i + 1), 2]) / nfreqs))
    sys.stdout.flush()
